//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MarasMVC.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class sklepEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new sklepEntities object using the connection string found in the 'sklepEntities' section of the application configuration file.
        /// </summary>
        public sklepEntities() : base("name=sklepEntities", "sklepEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sklepEntities object.
        /// </summary>
        public sklepEntities(string connectionString) : base(connectionString, "sklepEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sklepEntities object.
        /// </summary>
        public sklepEntities(EntityConnection connection) : base(connection, "sklepEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Adres> Adres
        {
            get
            {
                if ((_Adres == null))
                {
                    _Adres = base.CreateObjectSet<Adres>("Adres");
                }
                return _Adres;
            }
        }
        private ObjectSet<Adres> _Adres;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Klinet> Klinet
        {
            get
            {
                if ((_Klinet == null))
                {
                    _Klinet = base.CreateObjectSet<Klinet>("Klinet");
                }
                return _Klinet;
            }
        }
        private ObjectSet<Klinet> _Klinet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pozycja_Zamowienia> Pozycja_Zamowienia
        {
            get
            {
                if ((_Pozycja_Zamowienia == null))
                {
                    _Pozycja_Zamowienia = base.CreateObjectSet<Pozycja_Zamowienia>("Pozycja_Zamowienia");
                }
                return _Pozycja_Zamowienia;
            }
        }
        private ObjectSet<Pozycja_Zamowienia> _Pozycja_Zamowienia;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PozycjaNaFakturze> PozycjaNaFakturze
        {
            get
            {
                if ((_PozycjaNaFakturze == null))
                {
                    _PozycjaNaFakturze = base.CreateObjectSet<PozycjaNaFakturze>("PozycjaNaFakturze");
                }
                return _PozycjaNaFakturze;
            }
        }
        private ObjectSet<PozycjaNaFakturze> _PozycjaNaFakturze;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Produkt> Produkt
        {
            get
            {
                if ((_Produkt == null))
                {
                    _Produkt = base.CreateObjectSet<Produkt>("Produkt");
                }
                return _Produkt;
            }
        }
        private ObjectSet<Produkt> _Produkt;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Rejestr_Faktur> Rejestr_Faktur
        {
            get
            {
                if ((_Rejestr_Faktur == null))
                {
                    _Rejestr_Faktur = base.CreateObjectSet<Rejestr_Faktur>("Rejestr_Faktur");
                }
                return _Rejestr_Faktur;
            }
        }
        private ObjectSet<Rejestr_Faktur> _Rejestr_Faktur;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RejestrZamowien> RejestrZamowien
        {
            get
            {
                if ((_RejestrZamowien == null))
                {
                    _RejestrZamowien = base.CreateObjectSet<RejestrZamowien>("RejestrZamowien");
                }
                return _RejestrZamowien;
            }
        }
        private ObjectSet<RejestrZamowien> _RejestrZamowien;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sprzedawca> Sprzedawca
        {
            get
            {
                if ((_Sprzedawca == null))
                {
                    _Sprzedawca = base.CreateObjectSet<Sprzedawca>("Sprzedawca");
                }
                return _Sprzedawca;
            }
        }
        private ObjectSet<Sprzedawca> _Sprzedawca;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Status_Zamowienia> Status_Zamowienia
        {
            get
            {
                if ((_Status_Zamowienia == null))
                {
                    _Status_Zamowienia = base.CreateObjectSet<Status_Zamowienia>("Status_Zamowienia");
                }
                return _Status_Zamowienia;
            }
        }
        private ObjectSet<Status_Zamowienia> _Status_Zamowienia;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Adres EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdres(Adres adres)
        {
            base.AddObject("Adres", adres);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Klinet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKlinet(Klinet klinet)
        {
            base.AddObject("Klinet", klinet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pozycja_Zamowienia EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPozycja_Zamowienia(Pozycja_Zamowienia pozycja_Zamowienia)
        {
            base.AddObject("Pozycja_Zamowienia", pozycja_Zamowienia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PozycjaNaFakturze EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPozycjaNaFakturze(PozycjaNaFakturze pozycjaNaFakturze)
        {
            base.AddObject("PozycjaNaFakturze", pozycjaNaFakturze);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Produkt EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProdukt(Produkt produkt)
        {
            base.AddObject("Produkt", produkt);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rejestr_Faktur EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRejestr_Faktur(Rejestr_Faktur rejestr_Faktur)
        {
            base.AddObject("Rejestr_Faktur", rejestr_Faktur);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RejestrZamowien EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRejestrZamowien(RejestrZamowien rejestrZamowien)
        {
            base.AddObject("RejestrZamowien", rejestrZamowien);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sprzedawca EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSprzedawca(Sprzedawca sprzedawca)
        {
            base.AddObject("Sprzedawca", sprzedawca);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Status_Zamowienia EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStatus_Zamowienia(Status_Zamowienia status_Zamowienia)
        {
            base.AddObject("Status_Zamowienia", status_Zamowienia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="Adres")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Adres : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Adres object.
        /// </summary>
        /// <param name="kod">Initial value of the Kod property.</param>
        /// <param name="nrKlienta">Initial value of the NrKlienta property.</param>
        /// <param name="ulica">Initial value of the Ulica property.</param>
        /// <param name="nrDomu">Initial value of the NrDomu property.</param>
        public static Adres CreateAdres(global::System.String kod, global::System.Decimal nrKlienta, global::System.String ulica, global::System.String nrDomu)
        {
            Adres adres = new Adres();
            adres.Kod = kod;
            adres.NrKlienta = nrKlienta;
            adres.Ulica = ulica;
            adres.NrDomu = nrDomu;
            return adres;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Kod
        {
            get
            {
                return _Kod;
            }
            set
            {
                if (_Kod != value)
                {
                    OnKodChanging(value);
                    ReportPropertyChanging("Kod");
                    _Kod = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Kod");
                    OnKodChanged();
                }
            }
        }
        private global::System.String _Kod;
        partial void OnKodChanging(global::System.String value);
        partial void OnKodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrKlienta
        {
            get
            {
                return _NrKlienta;
            }
            set
            {
                OnNrKlientaChanging(value);
                ReportPropertyChanging("NrKlienta");
                _NrKlienta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NrKlienta");
                OnNrKlientaChanged();
            }
        }
        private global::System.Decimal _NrKlienta;
        partial void OnNrKlientaChanging(global::System.Decimal value);
        partial void OnNrKlientaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Miasto
        {
            get
            {
                return _Miasto;
            }
            set
            {
                OnMiastoChanging(value);
                ReportPropertyChanging("Miasto");
                _Miasto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Miasto");
                OnMiastoChanged();
            }
        }
        private global::System.String _Miasto;
        partial void OnMiastoChanging(global::System.String value);
        partial void OnMiastoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ulica
        {
            get
            {
                return _Ulica;
            }
            set
            {
                OnUlicaChanging(value);
                ReportPropertyChanging("Ulica");
                _Ulica = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ulica");
                OnUlicaChanged();
            }
        }
        private global::System.String _Ulica;
        partial void OnUlicaChanging(global::System.String value);
        partial void OnUlicaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NrDomu
        {
            get
            {
                return _NrDomu;
            }
            set
            {
                OnNrDomuChanging(value);
                ReportPropertyChanging("NrDomu");
                _NrDomu = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NrDomu");
                OnNrDomuChanged();
            }
        }
        private global::System.String _NrDomu;
        partial void OnNrDomuChanging(global::System.String value);
        partial void OnNrDomuChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="Klinet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Klinet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Klinet object.
        /// </summary>
        /// <param name="nrKlienta">Initial value of the NrKlienta property.</param>
        /// <param name="imie">Initial value of the Imie property.</param>
        /// <param name="nazwisko">Initial value of the Nazwisko property.</param>
        /// <param name="e_Mail">Initial value of the E_Mail property.</param>
        /// <param name="nIP">Initial value of the NIP property.</param>
        /// <param name="telefon">Initial value of the Telefon property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="rola_w_systemie">Initial value of the Rola_w_systemie property.</param>
        public static Klinet CreateKlinet(global::System.Decimal nrKlienta, global::System.String imie, global::System.String nazwisko, global::System.String e_Mail, global::System.String nIP, global::System.String telefon, global::System.String login, global::System.String rola_w_systemie)
        {
            Klinet klinet = new Klinet();
            klinet.NrKlienta = nrKlienta;
            klinet.Imie = imie;
            klinet.Nazwisko = nazwisko;
            klinet.E_Mail = e_Mail;
            klinet.NIP = nIP;
            klinet.Telefon = telefon;
            klinet.Login = login;
            klinet.Rola_w_systemie = rola_w_systemie;
            return klinet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrKlienta
        {
            get
            {
                return _NrKlienta;
            }
            set
            {
                if (_NrKlienta != value)
                {
                    OnNrKlientaChanging(value);
                    ReportPropertyChanging("NrKlienta");
                    _NrKlienta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NrKlienta");
                    OnNrKlientaChanged();
                }
            }
        }
        private global::System.Decimal _NrKlienta;
        partial void OnNrKlientaChanging(global::System.Decimal value);
        partial void OnNrKlientaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Imie
        {
            get
            {
                return _Imie;
            }
            set
            {
                OnImieChanging(value);
                ReportPropertyChanging("Imie");
                _Imie = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Imie");
                OnImieChanged();
            }
        }
        private global::System.String _Imie;
        partial void OnImieChanging(global::System.String value);
        partial void OnImieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nazwisko
        {
            get
            {
                return _Nazwisko;
            }
            set
            {
                OnNazwiskoChanging(value);
                ReportPropertyChanging("Nazwisko");
                _Nazwisko = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nazwisko");
                OnNazwiskoChanged();
            }
        }
        private global::System.String _Nazwisko;
        partial void OnNazwiskoChanging(global::System.String value);
        partial void OnNazwiskoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String E_Mail
        {
            get
            {
                return _E_Mail;
            }
            set
            {
                OnE_MailChanging(value);
                ReportPropertyChanging("E_Mail");
                _E_Mail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("E_Mail");
                OnE_MailChanged();
            }
        }
        private global::System.String _E_Mail;
        partial void OnE_MailChanging(global::System.String value);
        partial void OnE_MailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NIP
        {
            get
            {
                return _NIP;
            }
            set
            {
                OnNIPChanging(value);
                ReportPropertyChanging("NIP");
                _NIP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NIP");
                OnNIPChanged();
            }
        }
        private global::System.String _NIP;
        partial void OnNIPChanging(global::System.String value);
        partial void OnNIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefon
        {
            get
            {
                return _Telefon;
            }
            set
            {
                OnTelefonChanging(value);
                ReportPropertyChanging("Telefon");
                _Telefon = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefon");
                OnTelefonChanged();
            }
        }
        private global::System.String _Telefon;
        partial void OnTelefonChanging(global::System.String value);
        partial void OnTelefonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OpisKlienta
        {
            get
            {
                return _OpisKlienta;
            }
            set
            {
                OnOpisKlientaChanging(value);
                ReportPropertyChanging("OpisKlienta");
                _OpisKlienta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OpisKlienta");
                OnOpisKlientaChanged();
            }
        }
        private global::System.String _OpisKlienta;
        partial void OnOpisKlientaChanging(global::System.String value);
        partial void OnOpisKlientaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Haslo
        {
            get
            {
                return _Haslo;
            }
            set
            {
                OnHasloChanging(value);
                ReportPropertyChanging("Haslo");
                _Haslo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Haslo");
                OnHasloChanged();
            }
        }
        private global::System.String _Haslo;
        partial void OnHasloChanging(global::System.String value);
        partial void OnHasloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Rola_w_systemie
        {
            get
            {
                return _Rola_w_systemie;
            }
            set
            {
                OnRola_w_systemieChanging(value);
                ReportPropertyChanging("Rola_w_systemie");
                _Rola_w_systemie = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Rola_w_systemie");
                OnRola_w_systemieChanged();
            }
        }
        private global::System.String _Rola_w_systemie;
        partial void OnRola_w_systemieChanging(global::System.String value);
        partial void OnRola_w_systemieChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="Pozycja_Zamowienia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pozycja_Zamowienia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pozycja_Zamowienia object.
        /// </summary>
        /// <param name="nrPozycjiZl">Initial value of the NrPozycjiZl property.</param>
        /// <param name="nrZamowienia">Initial value of the NrZamowienia property.</param>
        /// <param name="nrProduktu">Initial value of the NrProduktu property.</param>
        public static Pozycja_Zamowienia CreatePozycja_Zamowienia(global::System.Decimal nrPozycjiZl, global::System.Decimal nrZamowienia, global::System.Decimal nrProduktu)
        {
            Pozycja_Zamowienia pozycja_Zamowienia = new Pozycja_Zamowienia();
            pozycja_Zamowienia.NrPozycjiZl = nrPozycjiZl;
            pozycja_Zamowienia.NrZamowienia = nrZamowienia;
            pozycja_Zamowienia.NrProduktu = nrProduktu;
            return pozycja_Zamowienia;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrPozycjiZl
        {
            get
            {
                return _NrPozycjiZl;
            }
            set
            {
                if (_NrPozycjiZl != value)
                {
                    OnNrPozycjiZlChanging(value);
                    ReportPropertyChanging("NrPozycjiZl");
                    _NrPozycjiZl = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NrPozycjiZl");
                    OnNrPozycjiZlChanged();
                }
            }
        }
        private global::System.Decimal _NrPozycjiZl;
        partial void OnNrPozycjiZlChanging(global::System.Decimal value);
        partial void OnNrPozycjiZlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrZamowienia
        {
            get
            {
                return _NrZamowienia;
            }
            set
            {
                OnNrZamowieniaChanging(value);
                ReportPropertyChanging("NrZamowienia");
                _NrZamowienia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NrZamowienia");
                OnNrZamowieniaChanged();
            }
        }
        private global::System.Decimal _NrZamowienia;
        partial void OnNrZamowieniaChanging(global::System.Decimal value);
        partial void OnNrZamowieniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrProduktu
        {
            get
            {
                return _NrProduktu;
            }
            set
            {
                OnNrProduktuChanging(value);
                ReportPropertyChanging("NrProduktu");
                _NrProduktu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NrProduktu");
                OnNrProduktuChanged();
            }
        }
        private global::System.Decimal _NrProduktu;
        partial void OnNrProduktuChanging(global::System.Decimal value);
        partial void OnNrProduktuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NazwaZl
        {
            get
            {
                return _NazwaZl;
            }
            set
            {
                OnNazwaZlChanging(value);
                ReportPropertyChanging("NazwaZl");
                _NazwaZl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NazwaZl");
                OnNazwaZlChanged();
            }
        }
        private global::System.String _NazwaZl;
        partial void OnNazwaZlChanging(global::System.String value);
        partial void OnNazwaZlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TypZl
        {
            get
            {
                return _TypZl;
            }
            set
            {
                OnTypZlChanging(value);
                ReportPropertyChanging("TypZl");
                _TypZl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TypZl");
                OnTypZlChanged();
            }
        }
        private Nullable<global::System.Int32> _TypZl;
        partial void OnTypZlChanging(Nullable<global::System.Int32> value);
        partial void OnTypZlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IloscZl
        {
            get
            {
                return _IloscZl;
            }
            set
            {
                OnIloscZlChanging(value);
                ReportPropertyChanging("IloscZl");
                _IloscZl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IloscZl");
                OnIloscZlChanged();
            }
        }
        private Nullable<global::System.Int32> _IloscZl;
        partial void OnIloscZlChanging(Nullable<global::System.Int32> value);
        partial void OnIloscZlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Uwagi
        {
            get
            {
                return _Uwagi;
            }
            set
            {
                OnUwagiChanging(value);
                ReportPropertyChanging("Uwagi");
                _Uwagi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Uwagi");
                OnUwagiChanged();
            }
        }
        private global::System.String _Uwagi;
        partial void OnUwagiChanging(global::System.String value);
        partial void OnUwagiChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="PozycjaNaFakturze")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PozycjaNaFakturze : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PozycjaNaFakturze object.
        /// </summary>
        /// <param name="nrPozycji">Initial value of the NrPozycji property.</param>
        /// <param name="nrFaktury">Initial value of the NrFaktury property.</param>
        /// <param name="nrProduktu">Initial value of the NrProduktu property.</param>
        /// <param name="iloscFaktura">Initial value of the IloscFaktura property.</param>
        public static PozycjaNaFakturze CreatePozycjaNaFakturze(global::System.Decimal nrPozycji, global::System.Decimal nrFaktury, global::System.Decimal nrProduktu, global::System.Decimal iloscFaktura)
        {
            PozycjaNaFakturze pozycjaNaFakturze = new PozycjaNaFakturze();
            pozycjaNaFakturze.NrPozycji = nrPozycji;
            pozycjaNaFakturze.NrFaktury = nrFaktury;
            pozycjaNaFakturze.NrProduktu = nrProduktu;
            pozycjaNaFakturze.IloscFaktura = iloscFaktura;
            return pozycjaNaFakturze;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrPozycji
        {
            get
            {
                return _NrPozycji;
            }
            set
            {
                if (_NrPozycji != value)
                {
                    OnNrPozycjiChanging(value);
                    ReportPropertyChanging("NrPozycji");
                    _NrPozycji = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NrPozycji");
                    OnNrPozycjiChanged();
                }
            }
        }
        private global::System.Decimal _NrPozycji;
        partial void OnNrPozycjiChanging(global::System.Decimal value);
        partial void OnNrPozycjiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrFaktury
        {
            get
            {
                return _NrFaktury;
            }
            set
            {
                OnNrFakturyChanging(value);
                ReportPropertyChanging("NrFaktury");
                _NrFaktury = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NrFaktury");
                OnNrFakturyChanged();
            }
        }
        private global::System.Decimal _NrFaktury;
        partial void OnNrFakturyChanging(global::System.Decimal value);
        partial void OnNrFakturyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrProduktu
        {
            get
            {
                return _NrProduktu;
            }
            set
            {
                OnNrProduktuChanging(value);
                ReportPropertyChanging("NrProduktu");
                _NrProduktu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NrProduktu");
                OnNrProduktuChanged();
            }
        }
        private global::System.Decimal _NrProduktu;
        partial void OnNrProduktuChanging(global::System.Decimal value);
        partial void OnNrProduktuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IloscFaktura
        {
            get
            {
                return _IloscFaktura;
            }
            set
            {
                OnIloscFakturaChanging(value);
                ReportPropertyChanging("IloscFaktura");
                _IloscFaktura = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IloscFaktura");
                OnIloscFakturaChanged();
            }
        }
        private global::System.Decimal _IloscFaktura;
        partial void OnIloscFakturaChanging(global::System.Decimal value);
        partial void OnIloscFakturaChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="Produkt")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produkt : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Produkt object.
        /// </summary>
        /// <param name="nrProduktu">Initial value of the NrProduktu property.</param>
        /// <param name="nazwaProduktu">Initial value of the NazwaProduktu property.</param>
        /// <param name="ilosc">Initial value of the Ilosc property.</param>
        /// <param name="cenaJednostkowa">Initial value of the CenaJednostkowa property.</param>
        public static Produkt CreateProdukt(global::System.Decimal nrProduktu, global::System.String nazwaProduktu, global::System.String ilosc, global::System.Decimal cenaJednostkowa)
        {
            Produkt produkt = new Produkt();
            produkt.NrProduktu = nrProduktu;
            produkt.NazwaProduktu = nazwaProduktu;
            produkt.Ilosc = ilosc;
            produkt.CenaJednostkowa = cenaJednostkowa;
            return produkt;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrProduktu
        {
            get
            {
                return _NrProduktu;
            }
            set
            {
                if (_NrProduktu != value)
                {
                    OnNrProduktuChanging(value);
                    ReportPropertyChanging("NrProduktu");
                    _NrProduktu = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NrProduktu");
                    OnNrProduktuChanged();
                }
            }
        }
        private global::System.Decimal _NrProduktu;
        partial void OnNrProduktuChanging(global::System.Decimal value);
        partial void OnNrProduktuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NazwaProduktu
        {
            get
            {
                return _NazwaProduktu;
            }
            set
            {
                OnNazwaProduktuChanging(value);
                ReportPropertyChanging("NazwaProduktu");
                _NazwaProduktu = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NazwaProduktu");
                OnNazwaProduktuChanged();
            }
        }
        private global::System.String _NazwaProduktu;
        partial void OnNazwaProduktuChanging(global::System.String value);
        partial void OnNazwaProduktuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TypProduktu
        {
            get
            {
                return _TypProduktu;
            }
            set
            {
                OnTypProduktuChanging(value);
                ReportPropertyChanging("TypProduktu");
                _TypProduktu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TypProduktu");
                OnTypProduktuChanged();
            }
        }
        private global::System.String _TypProduktu;
        partial void OnTypProduktuChanging(global::System.String value);
        partial void OnTypProduktuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ilosc
        {
            get
            {
                return _Ilosc;
            }
            set
            {
                OnIloscChanging(value);
                ReportPropertyChanging("Ilosc");
                _Ilosc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ilosc");
                OnIloscChanged();
            }
        }
        private global::System.String _Ilosc;
        partial void OnIloscChanging(global::System.String value);
        partial void OnIloscChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CenaJednostkowa
        {
            get
            {
                return _CenaJednostkowa;
            }
            set
            {
                OnCenaJednostkowaChanging(value);
                ReportPropertyChanging("CenaJednostkowa");
                _CenaJednostkowa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CenaJednostkowa");
                OnCenaJednostkowaChanged();
            }
        }
        private global::System.Decimal _CenaJednostkowa;
        partial void OnCenaJednostkowaChanging(global::System.Decimal value);
        partial void OnCenaJednostkowaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Jednostka
        {
            get
            {
                return _Jednostka;
            }
            set
            {
                OnJednostkaChanging(value);
                ReportPropertyChanging("Jednostka");
                _Jednostka = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Jednostka");
                OnJednostkaChanged();
            }
        }
        private global::System.String _Jednostka;
        partial void OnJednostkaChanging(global::System.String value);
        partial void OnJednostkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OpisProduktu
        {
            get
            {
                return _OpisProduktu;
            }
            set
            {
                OnOpisProduktuChanging(value);
                ReportPropertyChanging("OpisProduktu");
                _OpisProduktu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OpisProduktu");
                OnOpisProduktuChanged();
            }
        }
        private global::System.String _OpisProduktu;
        partial void OnOpisProduktuChanging(global::System.String value);
        partial void OnOpisProduktuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RokProdukcji
        {
            get
            {
                return _RokProdukcji;
            }
            set
            {
                OnRokProdukcjiChanging(value);
                ReportPropertyChanging("RokProdukcji");
                _RokProdukcji = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RokProdukcji");
                OnRokProdukcjiChanged();
            }
        }
        private Nullable<global::System.DateTime> _RokProdukcji;
        partial void OnRokProdukcjiChanging(Nullable<global::System.DateTime> value);
        partial void OnRokProdukcjiChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="Rejestr_Faktur")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rejestr_Faktur : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Rejestr_Faktur object.
        /// </summary>
        /// <param name="nrFaktury">Initial value of the NrFaktury property.</param>
        /// <param name="nrKlienta">Initial value of the NrKlienta property.</param>
        /// <param name="terminPlatnosci">Initial value of the TerminPlatnosci property.</param>
        public static Rejestr_Faktur CreateRejestr_Faktur(global::System.Decimal nrFaktury, global::System.Decimal nrKlienta, global::System.DateTime terminPlatnosci)
        {
            Rejestr_Faktur rejestr_Faktur = new Rejestr_Faktur();
            rejestr_Faktur.NrFaktury = nrFaktury;
            rejestr_Faktur.NrKlienta = nrKlienta;
            rejestr_Faktur.TerminPlatnosci = terminPlatnosci;
            return rejestr_Faktur;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrFaktury
        {
            get
            {
                return _NrFaktury;
            }
            set
            {
                if (_NrFaktury != value)
                {
                    OnNrFakturyChanging(value);
                    ReportPropertyChanging("NrFaktury");
                    _NrFaktury = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NrFaktury");
                    OnNrFakturyChanged();
                }
            }
        }
        private global::System.Decimal _NrFaktury;
        partial void OnNrFakturyChanging(global::System.Decimal value);
        partial void OnNrFakturyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrKlienta
        {
            get
            {
                return _NrKlienta;
            }
            set
            {
                OnNrKlientaChanging(value);
                ReportPropertyChanging("NrKlienta");
                _NrKlienta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NrKlienta");
                OnNrKlientaChanged();
            }
        }
        private global::System.Decimal _NrKlienta;
        partial void OnNrKlientaChanging(global::System.Decimal value);
        partial void OnNrKlientaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TerminPlatnosci
        {
            get
            {
                return _TerminPlatnosci;
            }
            set
            {
                OnTerminPlatnosciChanging(value);
                ReportPropertyChanging("TerminPlatnosci");
                _TerminPlatnosci = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TerminPlatnosci");
                OnTerminPlatnosciChanged();
            }
        }
        private global::System.DateTime _TerminPlatnosci;
        partial void OnTerminPlatnosciChanging(global::System.DateTime value);
        partial void OnTerminPlatnosciChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="RejestrZamowien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RejestrZamowien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RejestrZamowien object.
        /// </summary>
        /// <param name="nrZamowienia">Initial value of the NrZamowienia property.</param>
        /// <param name="nrKlienta">Initial value of the NrKlienta property.</param>
        /// <param name="rodzajTranzakcji">Initial value of the RodzajTranzakcji property.</param>
        /// <param name="wartoscZamowienia">Initial value of the WartoscZamowienia property.</param>
        public static RejestrZamowien CreateRejestrZamowien(global::System.Decimal nrZamowienia, global::System.Decimal nrKlienta, global::System.String rodzajTranzakcji, global::System.Decimal wartoscZamowienia)
        {
            RejestrZamowien rejestrZamowien = new RejestrZamowien();
            rejestrZamowien.NrZamowienia = nrZamowienia;
            rejestrZamowien.NrKlienta = nrKlienta;
            rejestrZamowien.RodzajTranzakcji = rodzajTranzakcji;
            rejestrZamowien.WartoscZamowienia = wartoscZamowienia;
            return rejestrZamowien;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrZamowienia
        {
            get
            {
                return _NrZamowienia;
            }
            set
            {
                if (_NrZamowienia != value)
                {
                    OnNrZamowieniaChanging(value);
                    ReportPropertyChanging("NrZamowienia");
                    _NrZamowienia = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NrZamowienia");
                    OnNrZamowieniaChanged();
                }
            }
        }
        private global::System.Decimal _NrZamowienia;
        partial void OnNrZamowieniaChanging(global::System.Decimal value);
        partial void OnNrZamowieniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> NrPracownika
        {
            get
            {
                return _NrPracownika;
            }
            set
            {
                OnNrPracownikaChanging(value);
                ReportPropertyChanging("NrPracownika");
                _NrPracownika = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NrPracownika");
                OnNrPracownikaChanged();
            }
        }
        private Nullable<global::System.Decimal> _NrPracownika;
        partial void OnNrPracownikaChanging(Nullable<global::System.Decimal> value);
        partial void OnNrPracownikaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrKlienta
        {
            get
            {
                return _NrKlienta;
            }
            set
            {
                OnNrKlientaChanging(value);
                ReportPropertyChanging("NrKlienta");
                _NrKlienta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NrKlienta");
                OnNrKlientaChanged();
            }
        }
        private global::System.Decimal _NrKlienta;
        partial void OnNrKlientaChanging(global::System.Decimal value);
        partial void OnNrKlientaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RodzajTranzakcji
        {
            get
            {
                return _RodzajTranzakcji;
            }
            set
            {
                OnRodzajTranzakcjiChanging(value);
                ReportPropertyChanging("RodzajTranzakcji");
                _RodzajTranzakcji = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RodzajTranzakcji");
                OnRodzajTranzakcjiChanged();
            }
        }
        private global::System.String _RodzajTranzakcji;
        partial void OnRodzajTranzakcjiChanging(global::System.String value);
        partial void OnRodzajTranzakcjiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal WartoscZamowienia
        {
            get
            {
                return _WartoscZamowienia;
            }
            set
            {
                OnWartoscZamowieniaChanging(value);
                ReportPropertyChanging("WartoscZamowienia");
                _WartoscZamowienia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WartoscZamowienia");
                OnWartoscZamowieniaChanged();
            }
        }
        private global::System.Decimal _WartoscZamowienia;
        partial void OnWartoscZamowieniaChanging(global::System.Decimal value);
        partial void OnWartoscZamowieniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data;
        partial void OnDataChanging(Nullable<global::System.DateTime> value);
        partial void OnDataChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="Sprzedawca")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sprzedawca : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sprzedawca object.
        /// </summary>
        /// <param name="nrPracownika">Initial value of the NrPracownika property.</param>
        /// <param name="imie">Initial value of the Imie property.</param>
        /// <param name="nazwisko">Initial value of the Nazwisko property.</param>
        /// <param name="stanowisko">Initial value of the Stanowisko property.</param>
        /// <param name="nIP">Initial value of the NIP property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="rola_w_systemie">Initial value of the Rola_w_systemie property.</param>
        public static Sprzedawca CreateSprzedawca(global::System.Decimal nrPracownika, global::System.String imie, global::System.String nazwisko, global::System.String stanowisko, global::System.String nIP, global::System.String login, global::System.String rola_w_systemie)
        {
            Sprzedawca sprzedawca = new Sprzedawca();
            sprzedawca.NrPracownika = nrPracownika;
            sprzedawca.Imie = imie;
            sprzedawca.Nazwisko = nazwisko;
            sprzedawca.Stanowisko = stanowisko;
            sprzedawca.NIP = nIP;
            sprzedawca.Login = login;
            sprzedawca.Rola_w_systemie = rola_w_systemie;
            return sprzedawca;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrPracownika
        {
            get
            {
                return _NrPracownika;
            }
            set
            {
                if (_NrPracownika != value)
                {
                    OnNrPracownikaChanging(value);
                    ReportPropertyChanging("NrPracownika");
                    _NrPracownika = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NrPracownika");
                    OnNrPracownikaChanged();
                }
            }
        }
        private global::System.Decimal _NrPracownika;
        partial void OnNrPracownikaChanging(global::System.Decimal value);
        partial void OnNrPracownikaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Imie
        {
            get
            {
                return _Imie;
            }
            set
            {
                OnImieChanging(value);
                ReportPropertyChanging("Imie");
                _Imie = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Imie");
                OnImieChanged();
            }
        }
        private global::System.String _Imie;
        partial void OnImieChanging(global::System.String value);
        partial void OnImieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nazwisko
        {
            get
            {
                return _Nazwisko;
            }
            set
            {
                OnNazwiskoChanging(value);
                ReportPropertyChanging("Nazwisko");
                _Nazwisko = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nazwisko");
                OnNazwiskoChanged();
            }
        }
        private global::System.String _Nazwisko;
        partial void OnNazwiskoChanging(global::System.String value);
        partial void OnNazwiskoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Stanowisko
        {
            get
            {
                return _Stanowisko;
            }
            set
            {
                OnStanowiskoChanging(value);
                ReportPropertyChanging("Stanowisko");
                _Stanowisko = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Stanowisko");
                OnStanowiskoChanged();
            }
        }
        private global::System.String _Stanowisko;
        partial void OnStanowiskoChanging(global::System.String value);
        partial void OnStanowiskoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NIP
        {
            get
            {
                return _NIP;
            }
            set
            {
                OnNIPChanging(value);
                ReportPropertyChanging("NIP");
                _NIP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NIP");
                OnNIPChanged();
            }
        }
        private global::System.String _NIP;
        partial void OnNIPChanging(global::System.String value);
        partial void OnNIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Rola_w_systemie
        {
            get
            {
                return _Rola_w_systemie;
            }
            set
            {
                OnRola_w_systemieChanging(value);
                ReportPropertyChanging("Rola_w_systemie");
                _Rola_w_systemie = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Rola_w_systemie");
                OnRola_w_systemieChanged();
            }
        }
        private global::System.String _Rola_w_systemie;
        partial void OnRola_w_systemieChanging(global::System.String value);
        partial void OnRola_w_systemieChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="Status_Zamowienia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Status_Zamowienia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Status_Zamowienia object.
        /// </summary>
        /// <param name="nrStatusu">Initial value of the NrStatusu property.</param>
        /// <param name="nrZamowienia">Initial value of the NrZamowienia property.</param>
        /// <param name="data">Initial value of the Data property.</param>
        public static Status_Zamowienia CreateStatus_Zamowienia(global::System.Decimal nrStatusu, global::System.Decimal nrZamowienia, global::System.DateTime data)
        {
            Status_Zamowienia status_Zamowienia = new Status_Zamowienia();
            status_Zamowienia.NrStatusu = nrStatusu;
            status_Zamowienia.NrZamowienia = nrZamowienia;
            status_Zamowienia.Data = data;
            return status_Zamowienia;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrStatusu
        {
            get
            {
                return _NrStatusu;
            }
            set
            {
                if (_NrStatusu != value)
                {
                    OnNrStatusuChanging(value);
                    ReportPropertyChanging("NrStatusu");
                    _NrStatusu = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NrStatusu");
                    OnNrStatusuChanged();
                }
            }
        }
        private global::System.Decimal _NrStatusu;
        partial void OnNrStatusuChanging(global::System.Decimal value);
        partial void OnNrStatusuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NrZamowienia
        {
            get
            {
                return _NrZamowienia;
            }
            set
            {
                OnNrZamowieniaChanging(value);
                ReportPropertyChanging("NrZamowienia");
                _NrZamowienia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NrZamowienia");
                OnNrZamowieniaChanged();
            }
        }
        private global::System.Decimal _NrZamowienia;
        partial void OnNrZamowieniaChanging(global::System.Decimal value);
        partial void OnNrZamowieniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.DateTime _Data;
        partial void OnDataChanging(global::System.DateTime value);
        partial void OnDataChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }

    #endregion
    
}
