//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4036
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 2010-01-10 13:45:48
namespace MarasMVC.Models
{
    
    /// <summary>
    /// There are no comments for sklepEntities in the schema.
    /// </summary>
    public partial class sklepEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new sklepEntities object using the connection string found in the 'sklepEntities' section of the application configuration file.
        /// </summary>
        public sklepEntities() : 
                base("name=sklepEntities", "sklepEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new sklepEntities object.
        /// </summary>
        public sklepEntities(string connectionString) : 
                base(connectionString, "sklepEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new sklepEntities object.
        /// </summary>
        public sklepEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "sklepEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Adres in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Adres> Adres
        {
            get
            {
                if ((this._Adres == null))
                {
                    this._Adres = base.CreateQuery<Adres>("[Adres]");
                }
                return this._Adres;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Adres> _Adres;
        /// <summary>
        /// There are no comments for Klinet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Klinet> Klinet
        {
            get
            {
                if ((this._Klinet == null))
                {
                    this._Klinet = base.CreateQuery<Klinet>("[Klinet]");
                }
                return this._Klinet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Klinet> _Klinet;
        /// <summary>
        /// There are no comments for Pozycja_Zamowienia in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Pozycja_Zamowienia> Pozycja_Zamowienia
        {
            get
            {
                if ((this._Pozycja_Zamowienia == null))
                {
                    this._Pozycja_Zamowienia = base.CreateQuery<Pozycja_Zamowienia>("[Pozycja_Zamowienia]");
                }
                return this._Pozycja_Zamowienia;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Pozycja_Zamowienia> _Pozycja_Zamowienia;
        /// <summary>
        /// There are no comments for PozycjaNaFakturze in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PozycjaNaFakturze> PozycjaNaFakturze
        {
            get
            {
                if ((this._PozycjaNaFakturze == null))
                {
                    this._PozycjaNaFakturze = base.CreateQuery<PozycjaNaFakturze>("[PozycjaNaFakturze]");
                }
                return this._PozycjaNaFakturze;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PozycjaNaFakturze> _PozycjaNaFakturze;
        /// <summary>
        /// There are no comments for Produkt in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Produkt> Produkt
        {
            get
            {
                if ((this._Produkt == null))
                {
                    this._Produkt = base.CreateQuery<Produkt>("[Produkt]");
                }
                return this._Produkt;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Produkt> _Produkt;
        /// <summary>
        /// There are no comments for Rejestr_Faktur in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Rejestr_Faktur> Rejestr_Faktur
        {
            get
            {
                if ((this._Rejestr_Faktur == null))
                {
                    this._Rejestr_Faktur = base.CreateQuery<Rejestr_Faktur>("[Rejestr_Faktur]");
                }
                return this._Rejestr_Faktur;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Rejestr_Faktur> _Rejestr_Faktur;
        /// <summary>
        /// There are no comments for RejestrZamowien in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<RejestrZamowien> RejestrZamowien
        {
            get
            {
                if ((this._RejestrZamowien == null))
                {
                    this._RejestrZamowien = base.CreateQuery<RejestrZamowien>("[RejestrZamowien]");
                }
                return this._RejestrZamowien;
            }
        }
        private global::System.Data.Objects.ObjectQuery<RejestrZamowien> _RejestrZamowien;
        /// <summary>
        /// There are no comments for Sprzedawca in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Sprzedawca> Sprzedawca
        {
            get
            {
                if ((this._Sprzedawca == null))
                {
                    this._Sprzedawca = base.CreateQuery<Sprzedawca>("[Sprzedawca]");
                }
                return this._Sprzedawca;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Sprzedawca> _Sprzedawca;
        /// <summary>
        /// There are no comments for Status_Zamowienia in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Status_Zamowienia> Status_Zamowienia
        {
            get
            {
                if ((this._Status_Zamowienia == null))
                {
                    this._Status_Zamowienia = base.CreateQuery<Status_Zamowienia>("[Status_Zamowienia]");
                }
                return this._Status_Zamowienia;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Status_Zamowienia> _Status_Zamowienia;
        /// <summary>
        /// There are no comments for sysdiagrams in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((this._sysdiagrams == null))
                {
                    this._sysdiagrams = base.CreateQuery<sysdiagrams>("[sysdiagrams]");
                }
                return this._sysdiagrams;
            }
        }
        private global::System.Data.Objects.ObjectQuery<sysdiagrams> _sysdiagrams;
        /// <summary>
        /// There are no comments for Adres in the schema.
        /// </summary>
        public void AddToAdres(Adres adres)
        {
            base.AddObject("Adres", adres);
        }
        /// <summary>
        /// There are no comments for Klinet in the schema.
        /// </summary>
        public void AddToKlinet(Klinet klinet)
        {
            base.AddObject("Klinet", klinet);
        }
        /// <summary>
        /// There are no comments for Pozycja_Zamowienia in the schema.
        /// </summary>
        public void AddToPozycja_Zamowienia(Pozycja_Zamowienia pozycja_Zamowienia)
        {
            base.AddObject("Pozycja_Zamowienia", pozycja_Zamowienia);
        }
        /// <summary>
        /// There are no comments for PozycjaNaFakturze in the schema.
        /// </summary>
        public void AddToPozycjaNaFakturze(PozycjaNaFakturze pozycjaNaFakturze)
        {
            base.AddObject("PozycjaNaFakturze", pozycjaNaFakturze);
        }
        /// <summary>
        /// There are no comments for Produkt in the schema.
        /// </summary>
        public void AddToProdukt(Produkt produkt)
        {
            base.AddObject("Produkt", produkt);
        }
        /// <summary>
        /// There are no comments for Rejestr_Faktur in the schema.
        /// </summary>
        public void AddToRejestr_Faktur(Rejestr_Faktur rejestr_Faktur)
        {
            base.AddObject("Rejestr_Faktur", rejestr_Faktur);
        }
        /// <summary>
        /// There are no comments for RejestrZamowien in the schema.
        /// </summary>
        public void AddToRejestrZamowien(RejestrZamowien rejestrZamowien)
        {
            base.AddObject("RejestrZamowien", rejestrZamowien);
        }
        /// <summary>
        /// There are no comments for Sprzedawca in the schema.
        /// </summary>
        public void AddToSprzedawca(Sprzedawca sprzedawca)
        {
            base.AddObject("Sprzedawca", sprzedawca);
        }
        /// <summary>
        /// There are no comments for Status_Zamowienia in the schema.
        /// </summary>
        public void AddToStatus_Zamowienia(Status_Zamowienia status_Zamowienia)
        {
            base.AddObject("Status_Zamowienia", status_Zamowienia);
        }
        /// <summary>
        /// There are no comments for sysdiagrams in the schema.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    }
    /// <summary>
    /// There are no comments for sklepModel.Adres in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Kod
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="Adres")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Adres : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Adres object.
        /// </summary>
        /// <param name="kod">Initial value of Kod.</param>
        /// <param name="nrKlienta">Initial value of NrKlienta.</param>
        /// <param name="ulica">Initial value of Ulica.</param>
        /// <param name="nrDomu">Initial value of NrDomu.</param>
        public static Adres CreateAdres(string kod, decimal nrKlienta, string ulica, string nrDomu)
        {
            Adres adres = new Adres();
            adres.Kod = kod;
            adres.NrKlienta = nrKlienta;
            adres.Ulica = ulica;
            adres.NrDomu = nrDomu;
            return adres;
        }
        /// <summary>
        /// There are no comments for Property Kod in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Kod
        {
            get
            {
                return this._Kod;
            }
            set
            {
                this.OnKodChanging(value);
                this.ReportPropertyChanging("Kod");
                this._Kod = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Kod");
                this.OnKodChanged();
            }
        }
        private string _Kod;
        partial void OnKodChanging(string value);
        partial void OnKodChanged();
        /// <summary>
        /// There are no comments for Property NrKlienta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrKlienta
        {
            get
            {
                return this._NrKlienta;
            }
            set
            {
                this.OnNrKlientaChanging(value);
                this.ReportPropertyChanging("NrKlienta");
                this._NrKlienta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrKlienta");
                this.OnNrKlientaChanged();
            }
        }
        private decimal _NrKlienta;
        partial void OnNrKlientaChanging(decimal value);
        partial void OnNrKlientaChanged();
        /// <summary>
        /// There are no comments for Property Miasto in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Miasto
        {
            get
            {
                return this._Miasto;
            }
            set
            {
                this.OnMiastoChanging(value);
                this.ReportPropertyChanging("Miasto");
                this._Miasto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Miasto");
                this.OnMiastoChanged();
            }
        }
        private string _Miasto;
        partial void OnMiastoChanging(string value);
        partial void OnMiastoChanged();
        /// <summary>
        /// There are no comments for Property Ulica in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulica
        {
            get
            {
                return this._Ulica;
            }
            set
            {
                this.OnUlicaChanging(value);
                this.ReportPropertyChanging("Ulica");
                this._Ulica = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Ulica");
                this.OnUlicaChanged();
            }
        }
        private string _Ulica;
        partial void OnUlicaChanging(string value);
        partial void OnUlicaChanged();
        /// <summary>
        /// There are no comments for Property NrDomu in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NrDomu
        {
            get
            {
                return this._NrDomu;
            }
            set
            {
                this.OnNrDomuChanging(value);
                this.ReportPropertyChanging("NrDomu");
                this._NrDomu = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NrDomu");
                this.OnNrDomuChanged();
            }
        }
        private string _NrDomu;
        partial void OnNrDomuChanging(string value);
        partial void OnNrDomuChanged();
    }
    /// <summary>
    /// There are no comments for sklepModel.Klinet in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NrKlienta
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="Klinet")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Klinet : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Klinet object.
        /// </summary>
        /// <param name="nrKlienta">Initial value of NrKlienta.</param>
        /// <param name="imie">Initial value of Imie.</param>
        /// <param name="nazwisko">Initial value of Nazwisko.</param>
        /// <param name="e_Mail">Initial value of E_Mail.</param>
        /// <param name="nIP">Initial value of NIP.</param>
        /// <param name="telefon">Initial value of Telefon.</param>
        /// <param name="login">Initial value of Login.</param>
        /// <param name="rola_w_systemie">Initial value of Rola_w_systemie.</param>
        public static Klinet CreateKlinet(decimal nrKlienta, string imie, string nazwisko, string e_Mail, string nIP, string telefon, string login, string rola_w_systemie)
        {
            Klinet klinet = new Klinet();
            klinet.NrKlienta = nrKlienta;
            klinet.Imie = imie;
            klinet.Nazwisko = nazwisko;
            klinet.E_Mail = e_Mail;
            klinet.NIP = nIP;
            klinet.Telefon = telefon;
            klinet.Login = login;
            klinet.Rola_w_systemie = rola_w_systemie;
            return klinet;
        }
        /// <summary>
        /// There are no comments for Property NrKlienta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrKlienta
        {
            get
            {
                return this._NrKlienta;
            }
            set
            {
                this.OnNrKlientaChanging(value);
                this.ReportPropertyChanging("NrKlienta");
                this._NrKlienta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrKlienta");
                this.OnNrKlientaChanged();
            }
        }
        private decimal _NrKlienta;
        partial void OnNrKlientaChanging(decimal value);
        partial void OnNrKlientaChanged();
        /// <summary>
        /// There are no comments for Property Imie in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie
        {
            get
            {
                return this._Imie;
            }
            set
            {
                this.OnImieChanging(value);
                this.ReportPropertyChanging("Imie");
                this._Imie = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Imie");
                this.OnImieChanged();
            }
        }
        private string _Imie;
        partial void OnImieChanging(string value);
        partial void OnImieChanged();
        /// <summary>
        /// There are no comments for Property Nazwisko in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko
        {
            get
            {
                return this._Nazwisko;
            }
            set
            {
                this.OnNazwiskoChanging(value);
                this.ReportPropertyChanging("Nazwisko");
                this._Nazwisko = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nazwisko");
                this.OnNazwiskoChanged();
            }
        }
        private string _Nazwisko;
        partial void OnNazwiskoChanging(string value);
        partial void OnNazwiskoChanged();
        /// <summary>
        /// There are no comments for Property E_Mail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string E_Mail
        {
            get
            {
                return this._E_Mail;
            }
            set
            {
                this.OnE_MailChanging(value);
                this.ReportPropertyChanging("E_Mail");
                this._E_Mail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("E_Mail");
                this.OnE_MailChanged();
            }
        }
        private string _E_Mail;
        partial void OnE_MailChanging(string value);
        partial void OnE_MailChanged();
        /// <summary>
        /// There are no comments for Property NIP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NIP
        {
            get
            {
                return this._NIP;
            }
            set
            {
                this.OnNIPChanging(value);
                this.ReportPropertyChanging("NIP");
                this._NIP = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NIP");
                this.OnNIPChanged();
            }
        }
        private string _NIP;
        partial void OnNIPChanging(string value);
        partial void OnNIPChanged();
        /// <summary>
        /// There are no comments for Property Telefon in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon
        {
            get
            {
                return this._Telefon;
            }
            set
            {
                this.OnTelefonChanging(value);
                this.ReportPropertyChanging("Telefon");
                this._Telefon = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Telefon");
                this.OnTelefonChanged();
            }
        }
        private string _Telefon;
        partial void OnTelefonChanging(string value);
        partial void OnTelefonChanged();
        /// <summary>
        /// There are no comments for Property OpisKlienta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string OpisKlienta
        {
            get
            {
                return this._OpisKlienta;
            }
            set
            {
                this.OnOpisKlientaChanging(value);
                this.ReportPropertyChanging("OpisKlienta");
                this._OpisKlienta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("OpisKlienta");
                this.OnOpisKlientaChanged();
            }
        }
        private string _OpisKlienta;
        partial void OnOpisKlientaChanging(string value);
        partial void OnOpisKlientaChanged();
        /// <summary>
        /// There are no comments for Property Haslo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Haslo
        {
            get
            {
                return this._Haslo;
            }
            set
            {
                this.OnHasloChanging(value);
                this.ReportPropertyChanging("Haslo");
                this._Haslo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Haslo");
                this.OnHasloChanged();
            }
        }
        private string _Haslo;
        partial void OnHasloChanging(string value);
        partial void OnHasloChanged();
        /// <summary>
        /// There are no comments for Property Login in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this._Login;
            }
            set
            {
                this.OnLoginChanging(value);
                this.ReportPropertyChanging("Login");
                this._Login = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Login");
                this.OnLoginChanged();
            }
        }
        private string _Login;
        partial void OnLoginChanging(string value);
        partial void OnLoginChanged();
        /// <summary>
        /// There are no comments for Property Rola_w_systemie in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Rola_w_systemie
        {
            get
            {
                return this._Rola_w_systemie;
            }
            set
            {
                this.OnRola_w_systemieChanging(value);
                this.ReportPropertyChanging("Rola_w_systemie");
                this._Rola_w_systemie = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Rola_w_systemie");
                this.OnRola_w_systemieChanged();
            }
        }
        private string _Rola_w_systemie;
        partial void OnRola_w_systemieChanging(string value);
        partial void OnRola_w_systemieChanged();
    }
    /// <summary>
    /// There are no comments for sklepModel.Pozycja_Zamowienia in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NrPozycjiZl
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="Pozycja_Zamowienia")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Pozycja_Zamowienia : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Pozycja_Zamowienia object.
        /// </summary>
        /// <param name="nrPozycjiZl">Initial value of NrPozycjiZl.</param>
        /// <param name="nrZamowienia">Initial value of NrZamowienia.</param>
        /// <param name="nrProduktu">Initial value of NrProduktu.</param>
        public static Pozycja_Zamowienia CreatePozycja_Zamowienia(decimal nrPozycjiZl, decimal nrZamowienia, decimal nrProduktu)
        {
            Pozycja_Zamowienia pozycja_Zamowienia = new Pozycja_Zamowienia();
            pozycja_Zamowienia.NrPozycjiZl = nrPozycjiZl;
            pozycja_Zamowienia.NrZamowienia = nrZamowienia;
            pozycja_Zamowienia.NrProduktu = nrProduktu;
            return pozycja_Zamowienia;
        }
        /// <summary>
        /// There are no comments for Property NrPozycjiZl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrPozycjiZl
        {
            get
            {
                return this._NrPozycjiZl;
            }
            set
            {
                this.OnNrPozycjiZlChanging(value);
                this.ReportPropertyChanging("NrPozycjiZl");
                this._NrPozycjiZl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrPozycjiZl");
                this.OnNrPozycjiZlChanged();
            }
        }
        private decimal _NrPozycjiZl;
        partial void OnNrPozycjiZlChanging(decimal value);
        partial void OnNrPozycjiZlChanged();
        /// <summary>
        /// There are no comments for Property NrZamowienia in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrZamowienia
        {
            get
            {
                return this._NrZamowienia;
            }
            set
            {
                this.OnNrZamowieniaChanging(value);
                this.ReportPropertyChanging("NrZamowienia");
                this._NrZamowienia = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrZamowienia");
                this.OnNrZamowieniaChanged();
            }
        }
        private decimal _NrZamowienia;
        partial void OnNrZamowieniaChanging(decimal value);
        partial void OnNrZamowieniaChanged();
        /// <summary>
        /// There are no comments for Property NrProduktu in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrProduktu
        {
            get
            {
                return this._NrProduktu;
            }
            set
            {
                this.OnNrProduktuChanging(value);
                this.ReportPropertyChanging("NrProduktu");
                this._NrProduktu = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrProduktu");
                this.OnNrProduktuChanged();
            }
        }
        private decimal _NrProduktu;
        partial void OnNrProduktuChanging(decimal value);
        partial void OnNrProduktuChanged();
        /// <summary>
        /// There are no comments for Property NazwaZl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NazwaZl
        {
            get
            {
                return this._NazwaZl;
            }
            set
            {
                this.OnNazwaZlChanging(value);
                this.ReportPropertyChanging("NazwaZl");
                this._NazwaZl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NazwaZl");
                this.OnNazwaZlChanged();
            }
        }
        private string _NazwaZl;
        partial void OnNazwaZlChanging(string value);
        partial void OnNazwaZlChanged();
        /// <summary>
        /// There are no comments for Property TypZl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> TypZl
        {
            get
            {
                return this._TypZl;
            }
            set
            {
                this.OnTypZlChanging(value);
                this.ReportPropertyChanging("TypZl");
                this._TypZl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TypZl");
                this.OnTypZlChanged();
            }
        }
        private global::System.Nullable<int> _TypZl;
        partial void OnTypZlChanging(global::System.Nullable<int> value);
        partial void OnTypZlChanged();
        /// <summary>
        /// There are no comments for Property IloscZl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> IloscZl
        {
            get
            {
                return this._IloscZl;
            }
            set
            {
                this.OnIloscZlChanging(value);
                this.ReportPropertyChanging("IloscZl");
                this._IloscZl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IloscZl");
                this.OnIloscZlChanged();
            }
        }
        private global::System.Nullable<int> _IloscZl;
        partial void OnIloscZlChanging(global::System.Nullable<int> value);
        partial void OnIloscZlChanged();
        /// <summary>
        /// There are no comments for Property Uwagi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Uwagi
        {
            get
            {
                return this._Uwagi;
            }
            set
            {
                this.OnUwagiChanging(value);
                this.ReportPropertyChanging("Uwagi");
                this._Uwagi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Uwagi");
                this.OnUwagiChanged();
            }
        }
        private string _Uwagi;
        partial void OnUwagiChanging(string value);
        partial void OnUwagiChanged();
    }
    /// <summary>
    /// There are no comments for sklepModel.PozycjaNaFakturze in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NrPozycji
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="PozycjaNaFakturze")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PozycjaNaFakturze : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PozycjaNaFakturze object.
        /// </summary>
        /// <param name="nrPozycji">Initial value of NrPozycji.</param>
        /// <param name="nrFaktury">Initial value of NrFaktury.</param>
        /// <param name="nrProduktu">Initial value of NrProduktu.</param>
        /// <param name="iloscFaktura">Initial value of IloscFaktura.</param>
        public static PozycjaNaFakturze CreatePozycjaNaFakturze(decimal nrPozycji, decimal nrFaktury, decimal nrProduktu, decimal iloscFaktura)
        {
            PozycjaNaFakturze pozycjaNaFakturze = new PozycjaNaFakturze();
            pozycjaNaFakturze.NrPozycji = nrPozycji;
            pozycjaNaFakturze.NrFaktury = nrFaktury;
            pozycjaNaFakturze.NrProduktu = nrProduktu;
            pozycjaNaFakturze.IloscFaktura = iloscFaktura;
            return pozycjaNaFakturze;
        }
        /// <summary>
        /// There are no comments for Property NrPozycji in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrPozycji
        {
            get
            {
                return this._NrPozycji;
            }
            set
            {
                this.OnNrPozycjiChanging(value);
                this.ReportPropertyChanging("NrPozycji");
                this._NrPozycji = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrPozycji");
                this.OnNrPozycjiChanged();
            }
        }
        private decimal _NrPozycji;
        partial void OnNrPozycjiChanging(decimal value);
        partial void OnNrPozycjiChanged();
        /// <summary>
        /// There are no comments for Property NrFaktury in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrFaktury
        {
            get
            {
                return this._NrFaktury;
            }
            set
            {
                this.OnNrFakturyChanging(value);
                this.ReportPropertyChanging("NrFaktury");
                this._NrFaktury = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrFaktury");
                this.OnNrFakturyChanged();
            }
        }
        private decimal _NrFaktury;
        partial void OnNrFakturyChanging(decimal value);
        partial void OnNrFakturyChanged();
        /// <summary>
        /// There are no comments for Property NrProduktu in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrProduktu
        {
            get
            {
                return this._NrProduktu;
            }
            set
            {
                this.OnNrProduktuChanging(value);
                this.ReportPropertyChanging("NrProduktu");
                this._NrProduktu = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrProduktu");
                this.OnNrProduktuChanged();
            }
        }
        private decimal _NrProduktu;
        partial void OnNrProduktuChanging(decimal value);
        partial void OnNrProduktuChanged();
        /// <summary>
        /// There are no comments for Property IloscFaktura in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IloscFaktura
        {
            get
            {
                return this._IloscFaktura;
            }
            set
            {
                this.OnIloscFakturaChanging(value);
                this.ReportPropertyChanging("IloscFaktura");
                this._IloscFaktura = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IloscFaktura");
                this.OnIloscFakturaChanged();
            }
        }
        private decimal _IloscFaktura;
        partial void OnIloscFakturaChanging(decimal value);
        partial void OnIloscFakturaChanged();
    }
    /// <summary>
    /// There are no comments for sklepModel.Produkt in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NrProduktu
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="Produkt")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Produkt : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Produkt object.
        /// </summary>
        /// <param name="nrProduktu">Initial value of NrProduktu.</param>
        /// <param name="nazwaProduktu">Initial value of NazwaProduktu.</param>
        /// <param name="ilosc">Initial value of Ilosc.</param>
        /// <param name="cenaJednostkowa">Initial value of CenaJednostkowa.</param>
        public static Produkt CreateProdukt(decimal nrProduktu, string nazwaProduktu, string ilosc, decimal cenaJednostkowa)
        {
            Produkt produkt = new Produkt();
            produkt.NrProduktu = nrProduktu;
            produkt.NazwaProduktu = nazwaProduktu;
            produkt.Ilosc = ilosc;
            produkt.CenaJednostkowa = cenaJednostkowa;
            return produkt;
        }
        /// <summary>
        /// There are no comments for Property NrProduktu in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrProduktu
        {
            get
            {
                return this._NrProduktu;
            }
            set
            {
                this.OnNrProduktuChanging(value);
                this.ReportPropertyChanging("NrProduktu");
                this._NrProduktu = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrProduktu");
                this.OnNrProduktuChanged();
            }
        }
        private decimal _NrProduktu;
        partial void OnNrProduktuChanging(decimal value);
        partial void OnNrProduktuChanged();
        /// <summary>
        /// There are no comments for Property NazwaProduktu in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NazwaProduktu
        {
            get
            {
                return this._NazwaProduktu;
            }
            set
            {
                this.OnNazwaProduktuChanging(value);
                this.ReportPropertyChanging("NazwaProduktu");
                this._NazwaProduktu = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NazwaProduktu");
                this.OnNazwaProduktuChanged();
            }
        }
        private string _NazwaProduktu;
        partial void OnNazwaProduktuChanging(string value);
        partial void OnNazwaProduktuChanged();
        /// <summary>
        /// There are no comments for Property TypProduktu in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TypProduktu
        {
            get
            {
                return this._TypProduktu;
            }
            set
            {
                this.OnTypProduktuChanging(value);
                this.ReportPropertyChanging("TypProduktu");
                this._TypProduktu = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TypProduktu");
                this.OnTypProduktuChanged();
            }
        }
        private string _TypProduktu;
        partial void OnTypProduktuChanging(string value);
        partial void OnTypProduktuChanged();
        /// <summary>
        /// There are no comments for Property Ilosc in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilosc
        {
            get
            {
                return this._Ilosc;
            }
            set
            {
                this.OnIloscChanging(value);
                this.ReportPropertyChanging("Ilosc");
                this._Ilosc = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Ilosc");
                this.OnIloscChanged();
            }
        }
        private string _Ilosc;
        partial void OnIloscChanging(string value);
        partial void OnIloscChanged();
        /// <summary>
        /// There are no comments for Property CenaJednostkowa in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CenaJednostkowa
        {
            get
            {
                return this._CenaJednostkowa;
            }
            set
            {
                this.OnCenaJednostkowaChanging(value);
                this.ReportPropertyChanging("CenaJednostkowa");
                this._CenaJednostkowa = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CenaJednostkowa");
                this.OnCenaJednostkowaChanged();
            }
        }
        private decimal _CenaJednostkowa;
        partial void OnCenaJednostkowaChanging(decimal value);
        partial void OnCenaJednostkowaChanged();
        /// <summary>
        /// There are no comments for Property Jednostka in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Jednostka
        {
            get
            {
                return this._Jednostka;
            }
            set
            {
                this.OnJednostkaChanging(value);
                this.ReportPropertyChanging("Jednostka");
                this._Jednostka = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Jednostka");
                this.OnJednostkaChanged();
            }
        }
        private string _Jednostka;
        partial void OnJednostkaChanging(string value);
        partial void OnJednostkaChanged();
        /// <summary>
        /// There are no comments for Property OpisProduktu in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string OpisProduktu
        {
            get
            {
                return this._OpisProduktu;
            }
            set
            {
                this.OnOpisProduktuChanging(value);
                this.ReportPropertyChanging("OpisProduktu");
                this._OpisProduktu = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("OpisProduktu");
                this.OnOpisProduktuChanged();
            }
        }
        private string _OpisProduktu;
        partial void OnOpisProduktuChanging(string value);
        partial void OnOpisProduktuChanged();
        /// <summary>
        /// There are no comments for Property RokProdukcji in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> RokProdukcji
        {
            get
            {
                return this._RokProdukcji;
            }
            set
            {
                this.OnRokProdukcjiChanging(value);
                this.ReportPropertyChanging("RokProdukcji");
                this._RokProdukcji = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RokProdukcji");
                this.OnRokProdukcjiChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _RokProdukcji;
        partial void OnRokProdukcjiChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnRokProdukcjiChanged();
    }
    /// <summary>
    /// There are no comments for sklepModel.Rejestr_Faktur in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NrFaktury
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="Rejestr_Faktur")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Rejestr_Faktur : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Rejestr_Faktur object.
        /// </summary>
        /// <param name="nrFaktury">Initial value of NrFaktury.</param>
        /// <param name="nrKlienta">Initial value of NrKlienta.</param>
        /// <param name="terminPlatnosci">Initial value of TerminPlatnosci.</param>
        public static Rejestr_Faktur CreateRejestr_Faktur(decimal nrFaktury, decimal nrKlienta, global::System.DateTime terminPlatnosci)
        {
            Rejestr_Faktur rejestr_Faktur = new Rejestr_Faktur();
            rejestr_Faktur.NrFaktury = nrFaktury;
            rejestr_Faktur.NrKlienta = nrKlienta;
            rejestr_Faktur.TerminPlatnosci = terminPlatnosci;
            return rejestr_Faktur;
        }
        /// <summary>
        /// There are no comments for Property NrFaktury in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrFaktury
        {
            get
            {
                return this._NrFaktury;
            }
            set
            {
                this.OnNrFakturyChanging(value);
                this.ReportPropertyChanging("NrFaktury");
                this._NrFaktury = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrFaktury");
                this.OnNrFakturyChanged();
            }
        }
        private decimal _NrFaktury;
        partial void OnNrFakturyChanging(decimal value);
        partial void OnNrFakturyChanged();
        /// <summary>
        /// There are no comments for Property NrKlienta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrKlienta
        {
            get
            {
                return this._NrKlienta;
            }
            set
            {
                this.OnNrKlientaChanging(value);
                this.ReportPropertyChanging("NrKlienta");
                this._NrKlienta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrKlienta");
                this.OnNrKlientaChanged();
            }
        }
        private decimal _NrKlienta;
        partial void OnNrKlientaChanging(decimal value);
        partial void OnNrKlientaChanged();
        /// <summary>
        /// There are no comments for Property TerminPlatnosci in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime TerminPlatnosci
        {
            get
            {
                return this._TerminPlatnosci;
            }
            set
            {
                this.OnTerminPlatnosciChanging(value);
                this.ReportPropertyChanging("TerminPlatnosci");
                this._TerminPlatnosci = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TerminPlatnosci");
                this.OnTerminPlatnosciChanged();
            }
        }
        private global::System.DateTime _TerminPlatnosci;
        partial void OnTerminPlatnosciChanging(global::System.DateTime value);
        partial void OnTerminPlatnosciChanged();
    }
    /// <summary>
    /// There are no comments for sklepModel.RejestrZamowien in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NrZamowienia
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="RejestrZamowien")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class RejestrZamowien : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new RejestrZamowien object.
        /// </summary>
        /// <param name="nrZamowienia">Initial value of NrZamowienia.</param>
        /// <param name="nrKlienta">Initial value of NrKlienta.</param>
        /// <param name="rodzajTranzakcji">Initial value of RodzajTranzakcji.</param>
        /// <param name="wartoscZamowienia">Initial value of WartoscZamowienia.</param>
        public static RejestrZamowien CreateRejestrZamowien(decimal nrZamowienia, decimal nrKlienta, string rodzajTranzakcji, decimal wartoscZamowienia)
        {
            RejestrZamowien rejestrZamowien = new RejestrZamowien();
            rejestrZamowien.NrZamowienia = nrZamowienia;
            rejestrZamowien.NrKlienta = nrKlienta;
            rejestrZamowien.RodzajTranzakcji = rodzajTranzakcji;
            rejestrZamowien.WartoscZamowienia = wartoscZamowienia;
            return rejestrZamowien;
        }
        /// <summary>
        /// There are no comments for Property NrZamowienia in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrZamowienia
        {
            get
            {
                return this._NrZamowienia;
            }
            set
            {
                this.OnNrZamowieniaChanging(value);
                this.ReportPropertyChanging("NrZamowienia");
                this._NrZamowienia = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrZamowienia");
                this.OnNrZamowieniaChanged();
            }
        }
        private decimal _NrZamowienia;
        partial void OnNrZamowieniaChanging(decimal value);
        partial void OnNrZamowieniaChanged();
        /// <summary>
        /// There are no comments for Property NrPracownika in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> NrPracownika
        {
            get
            {
                return this._NrPracownika;
            }
            set
            {
                this.OnNrPracownikaChanging(value);
                this.ReportPropertyChanging("NrPracownika");
                this._NrPracownika = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrPracownika");
                this.OnNrPracownikaChanged();
            }
        }
        private global::System.Nullable<decimal> _NrPracownika;
        partial void OnNrPracownikaChanging(global::System.Nullable<decimal> value);
        partial void OnNrPracownikaChanged();
        /// <summary>
        /// There are no comments for Property NrKlienta in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrKlienta
        {
            get
            {
                return this._NrKlienta;
            }
            set
            {
                this.OnNrKlientaChanging(value);
                this.ReportPropertyChanging("NrKlienta");
                this._NrKlienta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrKlienta");
                this.OnNrKlientaChanged();
            }
        }
        private decimal _NrKlienta;
        partial void OnNrKlientaChanging(decimal value);
        partial void OnNrKlientaChanged();
        /// <summary>
        /// There are no comments for Property RodzajTranzakcji in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RodzajTranzakcji
        {
            get
            {
                return this._RodzajTranzakcji;
            }
            set
            {
                this.OnRodzajTranzakcjiChanging(value);
                this.ReportPropertyChanging("RodzajTranzakcji");
                this._RodzajTranzakcji = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("RodzajTranzakcji");
                this.OnRodzajTranzakcjiChanged();
            }
        }
        private string _RodzajTranzakcji;
        partial void OnRodzajTranzakcjiChanging(string value);
        partial void OnRodzajTranzakcjiChanged();
        /// <summary>
        /// There are no comments for Property WartoscZamowienia in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal WartoscZamowienia
        {
            get
            {
                return this._WartoscZamowienia;
            }
            set
            {
                this.OnWartoscZamowieniaChanging(value);
                this.ReportPropertyChanging("WartoscZamowienia");
                this._WartoscZamowienia = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("WartoscZamowienia");
                this.OnWartoscZamowieniaChanged();
            }
        }
        private decimal _WartoscZamowienia;
        partial void OnWartoscZamowieniaChanging(decimal value);
        partial void OnWartoscZamowieniaChanged();
        /// <summary>
        /// There are no comments for Property Data in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> Data
        {
            get
            {
                return this._Data;
            }
            set
            {
                this.OnDataChanging(value);
                this.ReportPropertyChanging("Data");
                this._Data = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Data");
                this.OnDataChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _Data;
        partial void OnDataChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDataChanged();
    }
    /// <summary>
    /// There are no comments for sklepModel.Sprzedawca in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NrPracownika
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="Sprzedawca")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Sprzedawca : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Sprzedawca object.
        /// </summary>
        /// <param name="nrPracownika">Initial value of NrPracownika.</param>
        /// <param name="imie">Initial value of Imie.</param>
        /// <param name="nazwisko">Initial value of Nazwisko.</param>
        /// <param name="stanowisko">Initial value of Stanowisko.</param>
        /// <param name="nIP">Initial value of NIP.</param>
        /// <param name="login">Initial value of Login.</param>
        /// <param name="rola_w_systemie">Initial value of Rola_w_systemie.</param>
        public static Sprzedawca CreateSprzedawca(decimal nrPracownika, string imie, string nazwisko, string stanowisko, string nIP, string login, string rola_w_systemie)
        {
            Sprzedawca sprzedawca = new Sprzedawca();
            sprzedawca.NrPracownika = nrPracownika;
            sprzedawca.Imie = imie;
            sprzedawca.Nazwisko = nazwisko;
            sprzedawca.Stanowisko = stanowisko;
            sprzedawca.NIP = nIP;
            sprzedawca.Login = login;
            sprzedawca.Rola_w_systemie = rola_w_systemie;
            return sprzedawca;
        }
        /// <summary>
        /// There are no comments for Property NrPracownika in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrPracownika
        {
            get
            {
                return this._NrPracownika;
            }
            set
            {
                this.OnNrPracownikaChanging(value);
                this.ReportPropertyChanging("NrPracownika");
                this._NrPracownika = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrPracownika");
                this.OnNrPracownikaChanged();
            }
        }
        private decimal _NrPracownika;
        partial void OnNrPracownikaChanging(decimal value);
        partial void OnNrPracownikaChanged();
        /// <summary>
        /// There are no comments for Property Imie in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie
        {
            get
            {
                return this._Imie;
            }
            set
            {
                this.OnImieChanging(value);
                this.ReportPropertyChanging("Imie");
                this._Imie = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Imie");
                this.OnImieChanged();
            }
        }
        private string _Imie;
        partial void OnImieChanging(string value);
        partial void OnImieChanged();
        /// <summary>
        /// There are no comments for Property Nazwisko in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko
        {
            get
            {
                return this._Nazwisko;
            }
            set
            {
                this.OnNazwiskoChanging(value);
                this.ReportPropertyChanging("Nazwisko");
                this._Nazwisko = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nazwisko");
                this.OnNazwiskoChanged();
            }
        }
        private string _Nazwisko;
        partial void OnNazwiskoChanging(string value);
        partial void OnNazwiskoChanged();
        /// <summary>
        /// There are no comments for Property Stanowisko in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Stanowisko
        {
            get
            {
                return this._Stanowisko;
            }
            set
            {
                this.OnStanowiskoChanging(value);
                this.ReportPropertyChanging("Stanowisko");
                this._Stanowisko = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Stanowisko");
                this.OnStanowiskoChanged();
            }
        }
        private string _Stanowisko;
        partial void OnStanowiskoChanging(string value);
        partial void OnStanowiskoChanged();
        /// <summary>
        /// There are no comments for Property NIP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NIP
        {
            get
            {
                return this._NIP;
            }
            set
            {
                this.OnNIPChanging(value);
                this.ReportPropertyChanging("NIP");
                this._NIP = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NIP");
                this.OnNIPChanged();
            }
        }
        private string _NIP;
        partial void OnNIPChanging(string value);
        partial void OnNIPChanged();
        /// <summary>
        /// There are no comments for Property Login in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this._Login;
            }
            set
            {
                this.OnLoginChanging(value);
                this.ReportPropertyChanging("Login");
                this._Login = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Login");
                this.OnLoginChanged();
            }
        }
        private string _Login;
        partial void OnLoginChanging(string value);
        partial void OnLoginChanged();
        /// <summary>
        /// There are no comments for Property Rola_w_systemie in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Rola_w_systemie
        {
            get
            {
                return this._Rola_w_systemie;
            }
            set
            {
                this.OnRola_w_systemieChanging(value);
                this.ReportPropertyChanging("Rola_w_systemie");
                this._Rola_w_systemie = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Rola_w_systemie");
                this.OnRola_w_systemieChanged();
            }
        }
        private string _Rola_w_systemie;
        partial void OnRola_w_systemieChanging(string value);
        partial void OnRola_w_systemieChanged();
    }
    /// <summary>
    /// There are no comments for sklepModel.Status_Zamowienia in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NrStatusu
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="Status_Zamowienia")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Status_Zamowienia : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Status_Zamowienia object.
        /// </summary>
        /// <param name="nrStatusu">Initial value of NrStatusu.</param>
        /// <param name="nrZamowienia">Initial value of NrZamowienia.</param>
        /// <param name="data">Initial value of Data.</param>
        public static Status_Zamowienia CreateStatus_Zamowienia(decimal nrStatusu, decimal nrZamowienia, global::System.DateTime data)
        {
            Status_Zamowienia status_Zamowienia = new Status_Zamowienia();
            status_Zamowienia.NrStatusu = nrStatusu;
            status_Zamowienia.NrZamowienia = nrZamowienia;
            status_Zamowienia.Data = data;
            return status_Zamowienia;
        }
        /// <summary>
        /// There are no comments for Property NrStatusu in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrStatusu
        {
            get
            {
                return this._NrStatusu;
            }
            set
            {
                this.OnNrStatusuChanging(value);
                this.ReportPropertyChanging("NrStatusu");
                this._NrStatusu = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrStatusu");
                this.OnNrStatusuChanged();
            }
        }
        private decimal _NrStatusu;
        partial void OnNrStatusuChanging(decimal value);
        partial void OnNrStatusuChanged();
        /// <summary>
        /// There are no comments for Property NrZamowienia in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NrZamowienia
        {
            get
            {
                return this._NrZamowienia;
            }
            set
            {
                this.OnNrZamowieniaChanging(value);
                this.ReportPropertyChanging("NrZamowienia");
                this._NrZamowienia = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NrZamowienia");
                this.OnNrZamowieniaChanged();
            }
        }
        private decimal _NrZamowienia;
        partial void OnNrZamowieniaChanging(decimal value);
        partial void OnNrZamowieniaChanged();
        /// <summary>
        /// There are no comments for Property Data in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Data
        {
            get
            {
                return this._Data;
            }
            set
            {
                this.OnDataChanging(value);
                this.ReportPropertyChanging("Data");
                this._Data = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Data");
                this.OnDataChanged();
            }
        }
        private global::System.DateTime _Data;
        partial void OnDataChanging(global::System.DateTime value);
        partial void OnDataChanged();
    }
    /// <summary>
    /// There are no comments for sklepModel.sysdiagrams in the schema.
    /// </summary>
    /// <KeyProperties>
    /// diagram_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="sklepModel", Name="sysdiagrams")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class sysdiagrams : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of name.</param>
        /// <param name="principal_id">Initial value of principal_id.</param>
        /// <param name="diagram_id">Initial value of diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(string name, int principal_id, int diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property principal_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int principal_id
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this.Onprincipal_idChanging(value);
                this.ReportPropertyChanging("principal_id");
                this._principal_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("principal_id");
                this.Onprincipal_idChanged();
            }
        }
        private int _principal_id;
        partial void Onprincipal_idChanging(int value);
        partial void Onprincipal_idChanged();
        /// <summary>
        /// There are no comments for Property diagram_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int diagram_id
        {
            get
            {
                return this._diagram_id;
            }
            set
            {
                this.Ondiagram_idChanging(value);
                this.ReportPropertyChanging("diagram_id");
                this._diagram_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("diagram_id");
                this.Ondiagram_idChanged();
            }
        }
        private int _diagram_id;
        partial void Ondiagram_idChanging(int value);
        partial void Ondiagram_idChanged();
        /// <summary>
        /// There are no comments for Property version in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> version
        {
            get
            {
                return this._version;
            }
            set
            {
                this.OnversionChanging(value);
                this.ReportPropertyChanging("version");
                this._version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("version");
                this.OnversionChanged();
            }
        }
        private global::System.Nullable<int> _version;
        partial void OnversionChanging(global::System.Nullable<int> value);
        partial void OnversionChanged();
        /// <summary>
        /// There are no comments for Property definition in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] definition
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._definition);
            }
            set
            {
                this.OndefinitionChanging(value);
                this.ReportPropertyChanging("definition");
                this._definition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("definition");
                this.OndefinitionChanged();
            }
        }
        private byte[] _definition;
        partial void OndefinitionChanging(byte[] value);
        partial void OndefinitionChanged();
    }
}
